export default defineEventHandler(async (event) => {
  const cities = [
    {
      label: 'Montréal',
      value: 'montreal',
      code: 'mtl',
      latitude: 45.50884,
      longitude: -73.58781,
    },
    {
      label: 'Quebec City',
      value: 'quebec-city',
      code: 'qc',
      latitude: 46.813878,
      longitude: -71.207981,
    },
    {
      label: 'Laval',
      value: 'laval',
      code: 'lav',
      latitude: 45.56995,
      longitude: -73.692,
    },
    {
      label: 'Gatineau',
      value: 'gatineau',
      code: 'gat',
      latitude: 45.47723,
      longitude: -75.70164,
    },
    {
      label: 'Longueuil',
      value: 'longueuil',
      code: 'lon',
      latitude: 45.53121,
      longitude: -73.51806,
    },
    {
      label: 'Sherbrooke',
      value: 'sherbrooke',
      code: 'she',
      latitude: 45.40008,
      longitude: -71.89908,
    },
    {
      label: 'Saguenay',
      value: 'saguenay',
      code: 'sag',
      latitude: 48.41675,
      longitude: -71.06573,
    },
    {
      label: 'Trois-Rivières',
      value: 'trois-rivieres',
      code: 'tro',
      latitude: 46.34515,
      longitude: -72.5477,
    },
    {
      label: 'Terrebonne',
      value: 'terrebonne',
      code: 'ter',
      latitude: 45.69291,
      longitude: -73.63245,
    },
    // Quebec regions
    {
      label: 'Chicoutimi',
      value: 'chicoutimi',
      code: 'chi',
      latitude: 48.4284,
      longitude: -71.0682,
    },
    {
      label: 'Rimouski',
      value: 'rimouski',
      code: 'rim',
      latitude: 48.4461,
      longitude: -68.5247,
    },
    {
      label: 'Drummondville',
      value: 'drummondville',
      code: 'dru',
      latitude: 45.8788,
      longitude: -72.4847,
    },
    {
      label: 'Granby',
      value: 'granby',
      code: 'gra',
      latitude: 45.4011,
      longitude: -72.7321,
    },
    {
      label: 'Saint-Hyacinthe',
      value: 'saint-hyacinthe',
      code: 'shy',
      latitude: 45.6255,
      longitude: -72.9464,
    },
    {
      label: 'Shawinigan',
      value: 'shawinigan',
      code: 'sha',
      latitude: 46.5633,
      longitude: -72.7491,
    },
    {
      label: 'Rouyn-Noranda',
      value: 'rouyn-noranda',
      code: 'rou',
      latitude: 48.2389,
      longitude: -79.0289,
    },
    {
      label: 'Saint-Georges',
      value: 'saint-georges',
      code: 'sge',
      latitude: 46.118,
      longitude: -70.668,
    },
    {
      label: 'Sept-Îles',
      value: 'sept-iles',
      code: 'sep',
      latitude: 50.211,
      longitude: -66.363,
    },
    {
      label: 'Magog',
      value: 'magog',
      code: 'mag',
      latitude: 45.271,
      longitude: -72.148,
    },
  ]
  return cities
})
